
namespace prism.web.service.Model
{
	public enum ResultTypes: int
	{
		// This file is auto-generated by the ResultTypes.tt T4 template. Do not edit this file directly.
		// Source SQL file: .\InitPrismDB.sql
		NotExecuted = 1,
		Pass = 2,
		Fail = 3,
		Blocked = 4,
		InProgress = 5,
		Hang = 6,
		Paused = 7,
		Aborted = 8,
	}
 }