
namespace prism.web.service.Model
{
	public enum ResultTypes: int
	{
		// This file is auto-generated by the ResultTypes.tt T4 template. Do not edit this file directly.
		// Source SQL file: .\InitPrismDB.sql
		NotExecuted = 0,
		Pass = 1,
		Fail = 2,
		Blocked = 3,
		InProgress = 4,
		Hang = 5,
		Paused = 6,
		Aborted = 7,
	}
 }