//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceUnderTest
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int machineId { get; set; }
        public Nullable<int> productId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TestMachine TestMachine { get; set; }
    }
}
