//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestManagementDBEntities : DbContext
    {
        public TestManagementDBEntities()
            : base("name=TestManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeviceUnderTest> DeviceUnderTests { get; set; }
        public virtual DbSet<GraphicTemplate> GraphicTemplates { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Release> Releases { get; set; }
        public virtual DbSet<ResultType> ResultTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Script> Scripts { get; set; }
        public virtual DbSet<ScriptRepository> ScriptRepositories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TestArtifact> TestArtifacts { get; set; }
        public virtual DbSet<TestBuild> TestBuilds { get; set; }
        public virtual DbSet<TestCase> TestCases { get; set; }
        public virtual DbSet<TestJob> TestJobs { get; set; }
        public virtual DbSet<TestJobParameter> TestJobParameters { get; set; }
        public virtual DbSet<TestJobReportTemplate> TestJobReportTemplates { get; set; }
        public virtual DbSet<TestMachine> TestMachines { get; set; }
        public virtual DbSet<TestPlan> TestPlans { get; set; }
        public virtual DbSet<TestPlanRecipe> TestPlanRecipes { get; set; }
        public virtual DbSet<TestReport> TestReports { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<TestSuite> TestSuites { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCredential> UserCredentials { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
    }
}
