//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestBuild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestBuild()
        {
            this.TestReports = new HashSet<TestReport>();
            this.TestResults = new HashSet<TestResult>();
        }
    
        public long id { get; set; }
        public int testJobId { get; set; }
        public System.DateTime timestamp { get; set; }
        public int buildResultId { get; set; }
        public int testResultId { get; set; }
        public System.Guid guid { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public double timeoutHours { get; set; }
    
        public virtual ResultType ResultType { get; set; }
        public virtual ResultType ResultType1 { get; set; }
        public virtual TestJob TestJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestReport> TestReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
