//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestJobParameter
    {
        public int id { get; set; }
        public int testJobId { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string defaultValue { get; set; }
    
        public virtual TestJob TestJob { get; set; }
    }
}
