//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPlanRecipe
    {
        public int id { get; set; }
        public int testPlanId { get; set; }
        public Nullable<int> testSuitId { get; set; }
        public Nullable<int> testCaseId { get; set; }
        public string schedual { get; set; }
    
        public virtual TestCase TestCase { get; set; }
        public virtual TestPlan TestPlan { get; set; }
        public virtual TestSuite TestSuite { get; set; }
    }
}
