//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public long id { get; set; }
        public long testBuildId { get; set; }
        public int TestResultId { get; set; }
    
        public virtual ResultType ResultType { get; set; }
        public virtual TestBuild TestBuild { get; set; }
    }
}
