//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestJobReportTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestJobReportTemplate()
        {
            this.TestReports = new HashSet<TestReport>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string template { get; set; }
        public Nullable<int> testJobId { get; set; }
        public string emailTo { get; set; }
        public string emailCc { get; set; }
        public string emailBcc { get; set; }
    
        public virtual TestJob TestJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestReport> TestReports { get; set; }
    }
}
