//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestJob()
        {
            this.TestBuilds = new HashSet<TestBuild>();
            this.TestCases = new HashSet<TestCase>();
            this.TestJobParameters = new HashSet<TestJobParameter>();
            this.TestJobReportTemplates = new HashSet<TestJobReportTemplate>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> credentialId { get; set; }
        public Nullable<int> defaultTestMachineId { get; set; }
        public Nullable<int> projectId { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestBuild> TestBuilds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCase> TestCases { get; set; }
        public virtual UserCredential UserCredential { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestJobParameter> TestJobParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestJobReportTemplate> TestJobReportTemplates { get; set; }
    }
}
