//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prism.model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserCredential()
        {
            this.TestJobs = new HashSet<TestJob>();
            this.TestMachines = new HashSet<TestMachine>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string token { get; set; }
        public string description { get; set; }
        public string createdby { get; set; }
        public string scope { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestJob> TestJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestMachine> TestMachines { get; set; }
    }
}
